baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'AnnaLostInCode'
theme = "anubis2"

[author]
name = "Anna Emmenegger"

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

readMore = true


[[params.social]]
id = "github"
url = "https://github.com/AnnaLostInCode"

[[params.social]]
id = "twitter"
url = "https://bsky.app/profile/annalostinspace.bsky.social"


[[menu.main]]
identifier = "godot"
name = "Godot"
url = "/posts/godot/"
weight = 1

[[menu.main]]
identifier = "passerelle"
name = "Passerelle"
url = "/passerelle/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3
